name: CI/CD Pipeline
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /root/amo-roistat-call-fix
            
            last_commit=$(git rev-parse HEAD)
            
            git pull origin master
            
            docker compose down
            docker compose pull
            docker compose up -d --build
            sleep 11
            
            if [ $(curl -s -o /dev/null -w "%{http_code}" http://localhost:84/) -eq 404 ]; then
              echo "Контейнер Django запущен успешно"
            else
              echo "Контейнер Django не запустился вывод логов:"
              docker logs amo-roistat-call-fix-app-1
              echo "Отмена изменений"
              
              git reset --hard $last_commit
              
              docker compose down
              docker compose pull
              docker compose up -d --build
              exit 1
            fi
